### ISSUE TITLE
Add support for Polygon w/i Infura plugin

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-infura#24]
![image](https://user-images.githubusercontent.com/3859395/155665638-b15edc50-c103-44bd-aaa3-11805c297e3f.png)

Depends on what we support for ecosystems

**Comment by fubuloubu** [comment]
https://docs.infura.io/infura/networks/ethereum/json-rpc-methods

**Comment by unparalleled-js** [comment]
is done
