### ISSUE TITLE
feat: add environment variables to readme

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape-infura#28]
### Overview

Provide a simple overview of what you wish to see added. Please include:

We should tell the users in the README.md to add the env var 

```bash
# Used by the `ape-infura` plugin
export WEB3_INFURA_PROJECT_ID=<YOUR_INFURA_PROJECT_ID>
# Used by the `ape-alchemy` plugin
export WEB3_ALCHEMY_API_KEY=<YOUR_ALCHEMY_KEY>
```
look at the README in alchemy for reference:
https://github.com/ApeWorX/ape-alchmey

**Comment by unparalleled-js** [comment]
is done
